org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.dev.parkerharrelson.grpc=info
org.slf4j.simpleLogger.log.io.grpc=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showShortLogName=true
